### ISSUE TITLE
Saludo

### ISSUE THREAD

**Issue by Blizz1800** [TretornESP/bloodmoon#1]
Hiii, esta genial el curso de OSDev bro ;) soy uno de los chicos q te pidio q lo hicieras y tengo q pedirte mil disculpas xq la verdad no he podido seguirlo como quisiera :'( y tambien q se q esta parte de github no es para esto, pero weno, queria decirte q aunq no vale mucho tienes mi apoyo y de verdad q me encantan los videos ;)

**Comment by TretornESP** [comment]
Me alegro un montón de que te esté gustando la serie!! Tu apoyo vale mucho (:

**Comment by Blizz1800** [comment]
Jjjj Genial :3 weno, aquí estaré siempre esperando a los primeros 5 minutos q tenga libre para ver los vídeos, ta genial en serio! ;3

Es muy difícil encontrar contenido relacionado a la serie, en redes en español, y tan bien hecho XD! Así q si, acá está mi apoyo incondicional 👍
